use_frameworks!
source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '10.0'

target 'CXAPIKit_Example' do
  pod 'CXAPIKit', :path => '../'

  target 'CXAPIKit_Tests' do
    inherit! :search_paths

    
  end
end


pod 'CXNetworking', :git=> 'git@github.com:shenchunxing/CXNetworking.git'
